# Generated by Django 4.2 on 2025-09-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionnote',
            name='receipt_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Nota'),
        ),
    ]
