# Generated by Django 4.2 on 2025-09-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-date_created'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'verbose_name': 'Ítem de Cotización', 'verbose_name_plural': 'Ítems de Cotización'},
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='dispatch_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='dispatch_notes.dispatchnote'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CONVERTED', 'Convertida a Despacho')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
