# Generated by Django 4.2 on 2025-09-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnnote',
            name='return_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Devolución'),
        ),
    ]
