# Generated by Django 4.2 on 2025-09-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_alter_returnnote_return_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnnote',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento'),
        ),
    ]
