# Generated by Django 4.2 on 2025-11-24 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20250929_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Orden'),
        ),
    ]
